from pathlib import Path
from dataclasses import dataclass
from html import escape
import os
import re
import calendar
from datetime import date, datetime, timedelta
from collections import defaultdict

import pandas as pd
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Alignment

DEFAULT_TERM_YEAR = 2026
CALENDAR_WEEKDAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
DEFAULT_LECTURE_WEEKDAYS = [0, 2, 4]
DEFAULT_LAB_WEEKDAYS = [1]
DEFAULT_LAB_DELIVERABLE_WEEKDAYS = [1]
# Weeks between a lab or project session and its deliverable deadline. 1 keeps the
# deadline after the session even when its weekday falls earlier in the week.
DEFAULT_LAB_DELIVERABLE_WEEK_OFFSET = 1
# The tutorial hash is due before its own lab, so it stays in the session's own week.
DEFAULT_TUTORIAL_HASH_WEEK_OFFSET = 0
DEFAULT_DISCUSSION_WEEKDAYS = [3]
DEFAULT_OFFICE_HOURS_WEEKDAYS = [4]
DEFAULT_HOMEWORK_WEEKDAYS = [6]
DEFAULT_EVENT_TIMES = {
    "lecture": ("11:15 AM", "12:05 PM"),
    "lab": ("", ""),
    "lab_deliverable": ("9:55 PM", "10:00 PM"),
    "tutorial_hash": ("9:55 PM", "10:00 PM"),
    "project_deliverable": ("9:55 PM", "10:00 PM"),
    "discussion": ("12:20 PM", "1:10 PM"),
    "office_hours": ("3:00 PM", "5:00 PM"),
    "homework": ("", "3:00 PM"),
}
LOCAL_TIMEZONE = "America/New_York"
FLAGGABLE_IMPORTANT_DATE = re.compile(
    r"holiday|classes suspended|recess|substitute|classes resume|study period|last day of classes",
    re.IGNORECASE,
)
WEEKDAY_NUMBERS = {
    "monday": 0,
    "mon": 0,
    "tuesday": 1,
    "tue": 1,
    "tues": 1,
    "wednesday": 2,
    "wed": 2,
    "thursday": 3,
    "thu": 3,
    "thurs": 3,
    "friday": 4,
    "fri": 4,
    "saturday": 5,
    "sat": 5,
    "sunday": 6,
    "sun": 6,
}


def resolve_child(root: Path, value: str | Path) -> Path:
    path = Path(value)
    return path if path.is_absolute() else root / path


@dataclass
class CourseSiteConfig:
    root: Path
    course_code: str = "COURSE"
    course_title: str | None = None
    public_env_var: str = "COURSE_PUBLIC_SITE"
    term_year: int = DEFAULT_TERM_YEAR
    instructor_inputs_dir: str | Path = "instructor_inputs"
    generated_outputs_dir: str | Path = "generated_outputs"
    docs_dir: str | Path = "docs"
    lecture_summary_filename: str = "lecture_summary.md"
    lab_summary_filename: str = "lab_summary.md"
    lecture_schedule_filename: str = "Lecture_schedules.md"
    lab_schedule_filename: str = "Lab_schedules.md"
    homework_schedule_filename: str = "Homework_schedule.md"
    exceptions_filename: str = "Exception_schedules.md"
    quiz_schedule_filename: str = "quiz_schedule.md"
    learning_objectives_filename: str = "learningObjectives.md"
    important_dates_filename: str = "important_dates.md"
    weekly_schedule_filename: str = "weekly_schedule.md"
    calendar_schedule_filename: str = "calendar_schedule.md"
    calendar_ics_filename: str = "course_calendar.ics"
    xlsx_filename: str = "Weekly Schedules.xlsx"
    docs_weekly_schedule_filename: str = "weekly_schedule.md"
    docs_calendar_schedule_filename: str = "calendar_schedule.md"
    docs_calendar_ics_filename: str = "course_calendar.ics"
    docs_lecture_summary_filename: str = "lecture_summary.md"
    docs_lab_summary_filename: str = "lab_summary.md"
    docs_learning_objectives_filename: str = "learning_objectives.md"
    output_sheet: str = "AutoGenerated Schedule"
    local_timezone: str = LOCAL_TIMEZONE

    def __post_init__(self):
        self.root = Path(self.root).resolve()
        self.course_title = self.course_title or self.course_code
        self.instructor_inputs = resolve_child(self.root, self.instructor_inputs_dir)
        self.generated_outputs = resolve_child(self.root, self.generated_outputs_dir)
        self.docs = resolve_child(self.root, self.docs_dir)
        self.lecture_file = self.instructor_inputs / self.lecture_summary_filename
        self.lab_file = self.instructor_inputs / self.lab_summary_filename
        self.lecture_schedule_file = self.instructor_inputs / self.lecture_schedule_filename
        self.lab_schedule_file = self.instructor_inputs / self.lab_schedule_filename
        self.homework_schedule_file = self.instructor_inputs / self.homework_schedule_filename
        self.exceptions_file = self.instructor_inputs / self.exceptions_filename
        self.quiz_schedule_file = self.instructor_inputs / self.quiz_schedule_filename
        self.learning_objectives_file = self.instructor_inputs / self.learning_objectives_filename
        self.important_dates_file = self.instructor_inputs / self.important_dates_filename
        self.xlsx_file = self.generated_outputs / self.xlsx_filename
        self.output_md = self.generated_outputs / self.weekly_schedule_filename
        self.output_calendar_md = self.generated_outputs / self.calendar_schedule_filename
        self.output_ics = self.generated_outputs / self.calendar_ics_filename

    @classmethod
    def for_repo(
        cls,
        root: Path,
        course_code: str,
        public_env_var: str | None = None,
        course_title: str | None = None,
        **overrides,
    ):
        env_var = public_env_var or f"{course_code}_PUBLIC_SITE"
        return cls(
            root=Path(root),
            course_code=course_code,
            course_title=course_title,
            public_env_var=env_var,
            **overrides,
        )

    @property
    def site_source_pages(self):
        return {
            self.output_md: self.docs_weekly_schedule_filename,
            self.output_calendar_md: self.docs_calendar_schedule_filename,
            self.output_ics: self.docs_calendar_ics_filename,
            self.lecture_file: self.docs_lecture_summary_filename,
            self.lab_file: self.docs_lab_summary_filename,
            self.learning_objectives_file: self.docs_learning_objectives_filename,
        }


def is_public_site_build(env_var: str):
    return os.environ.get(env_var, "").lower() in {"1", "true", "yes", "public"}


def clean_text(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def normalize_objective_text(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return clean_text(text)


def normalize_dash(text: str) -> str:
    return text.replace("–", "-").replace("—", "-")


def parse_month_day(month_day: str, default_year: int) -> date:
    m = re.match(r"^([A-Za-z]+)\s+(\d{1,2})$", month_day.strip())
    if not m:
        raise ValueError(f"Could not parse date: {month_day}")

    month_name, day = m.groups()
    month = list(calendar.month_name).index(month_name)
    year = default_year if month >= 8 else default_year + 1
    return date(year, month, int(day))


def parse_schedule_date(text: str, default_year: int) -> date:
    text = clean_text(text)
    for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%m/%d"):
        try:
            parsed = datetime.strptime(text, fmt)
            year = parsed.year if "%Y" in fmt else default_year if parsed.month >= 8 else default_year + 1
            return date(year, parsed.month, parsed.day)
        except ValueError:
            continue
    return parse_month_day(text, default_year)


def split_markdown_table_row(line: str):
    if not line.startswith("|") or not line.endswith("|"):
        return None
    return [cell.strip() for cell in line.strip("|").split("|")]


def is_markdown_separator(cells):
    return all(re.fullmatch(r":?-{3,}:?", cell.strip()) for cell in cells)


def extract_table_after_heading(lines, heading: str):
    in_section = False
    table = []
    heading_pattern = re.compile(rf"^##\s+{re.escape(heading)}\s*$", re.IGNORECASE)

    for raw in lines:
        line = raw.rstrip()
        if heading_pattern.match(line):
            in_section = True
            continue
        if not in_section:
            continue
        if line.startswith("## ") and table:
            break

        cells = split_markdown_table_row(clean_text(line))
        if cells:
            table.append(cells)
        elif table:
            break

    if not table:
        return []

    headers = None
    rows = []
    for cells in table:
        if is_markdown_separator(cells):
            continue
        if headers is None:
            headers = [cell.lower() for cell in cells]
            continue
        rows.append(dict(zip(headers, cells)))
    return rows


def parse_weekday_list(text: str):
    weekdays = []
    parts = re.split(r",|/|;|\band\b", text, flags=re.IGNORECASE)
    for part in parts:
        key = clean_text(part).lower()
        if key in WEEKDAY_NUMBERS:
            weekdays.append(WEEKDAY_NUMBERS[key])
    return weekdays


def normalize_event_time(text: str):
    text = clean_text(text)
    if not text:
        return ""
    for fmt in ("%I:%M %p", "%I:%M%p", "%I %p", "%I%p", "%H:%M"):
        try:
            return datetime.strptime(text.upper(), fmt).strftime("%I:%M %p").lstrip("0")
        except ValueError:
            continue
    return text


def read_row_time(row, fallback):
    start = normalize_event_time(row.get("start time", ""))
    end = normalize_event_time(row.get("end time", ""))
    if not start and not end:
        start, end = fallback
    return start, end


def read_week_offset(row, fallback: int, source_name: str = "the lab schedule"):
    text = clean_text(row.get("weeks after", "") or row.get("weeks after session", ""))
    if not text:
        return fallback
    try:
        return int(text)
    except ValueError:
        raise ValueError(
            f"Could not read 'Weeks After' for {row.get('event type', 'the deliverable row')!r} "
            f"in {source_name}: {text!r}. Use a whole number such as 0 or 1."
        ) from None


def event_time_range(meeting_patterns, event_key: str):
    return meeting_patterns.get("times", {}).get(event_key, DEFAULT_EVENT_TIMES[event_key])


def format_time_range(start: str, end: str):
    if start and end:
        return f"{start}-{end}"
    if end:
        return f"Due {end}"
    if start:
        return f"Starts {start}"
    return ""


def time_for_ics(event_date: date, time_text: str):
    parsed = datetime.strptime(normalize_event_time(time_text), "%I:%M %p")
    return datetime.combine(event_date, parsed.time())


TUTORIAL_DELIVERABLE_PATTERN = re.compile(r"\btutorial\s+\d+\s+hash\b", re.IGNORECASE)


def split_tutorial_deliverables(deliverables: str):
    """Separate tutorial-hash items from the rest, since the two have different deadlines."""
    tutorial_items, other_items = [], []
    for item in (part.strip() for part in (deliverables or "").split("|")):
        if not item:
            continue
        (tutorial_items if TUTORIAL_DELIVERABLE_PATTERN.search(item) else other_items).append(item)
    return tutorial_items, other_items


def normalize_session_key(text: str) -> str:
    """Match a session name loosely, so "Project1-1", "project 1-1" and "P1-1" agree."""
    key = re.sub(r"[^a-z0-9]+", "", clean_text(text).lower())
    return re.sub(r"^project", "p", key)


def parse_session_overrides(lab_path: Path, default_year: int):
    """Read the optional "Session Overrides" table, where an instructor pins exact dates.

    Returns {session key: {"date": date | None, "deliverable_date": date | None}}. A blank
    cell means "keep deriving this one from the meeting pattern".
    """
    overrides = {}
    rows = extract_table_after_heading(
        lab_path.read_text(encoding="utf-8").splitlines(),
        "Session Overrides",
    )
    for row in rows:
        key = normalize_session_key(row.get("session", ""))
        if not key:
            continue
        entry = {}
        for column, field in (
            ("meets", "date"),
            ("deliverable due", "deliverable_date"),
            ("tutorial due", "tutorial_date"),
        ):
            text = clean_text(row.get(column, ""))
            if not text:
                continue
            try:
                entry[field] = parse_schedule_date(text, default_year)
            except (ValueError, TypeError):
                raise ValueError(
                    f"Could not read {column!r} for session {row.get('session', '')!r} "
                    f"in {lab_path.name}: {text!r}. Use a form like 2026-09-08 or 9/8/2026."
                ) from None
        if entry:
            overrides[key] = entry
    return overrides


def parse_meeting_patterns(lecture_path: Path, lab_path: Path, default_year: int = DEFAULT_TERM_YEAR):
    patterns = {
        "lecture": DEFAULT_LECTURE_WEEKDAYS,
        "lab": DEFAULT_LAB_WEEKDAYS,
        "lab_deliverable": DEFAULT_LAB_DELIVERABLE_WEEKDAYS,
        "lab_deliverable_week_offset": DEFAULT_LAB_DELIVERABLE_WEEK_OFFSET,
        "tutorial_hash": None,
        "tutorial_hash_week_offset": DEFAULT_TUTORIAL_HASH_WEEK_OFFSET,
        "project_deliverable": None,
        "project_deliverable_week_offset": None,
        "session_overrides": {},
        "discussion": DEFAULT_DISCUSSION_WEEKDAYS,
        "office_hours": DEFAULT_OFFICE_HOURS_WEEKDAYS,
        "times": DEFAULT_EVENT_TIMES.copy(),
        "discussion_patterns": [],
        "office_hour_patterns": [],
    }

    lecture_rows = extract_table_after_heading(
        lecture_path.read_text(encoding="utf-8").splitlines(),
        "Course Meeting Pattern",
    )
    for row in lecture_rows:
        event_type = row.get("event type", "").lower()
        weekdays = parse_weekday_list(row.get("weekdays", ""))
        if not weekdays:
            continue
        if event_type == "lecture":
            patterns["lecture"] = weekdays
            patterns["times"]["lecture"] = read_row_time(row, DEFAULT_EVENT_TIMES["lecture"])
        elif event_type == "discussion" or event_type.startswith("discussion "):
            patterns["discussion"] = weekdays
            patterns["times"]["discussion"] = read_row_time(row, DEFAULT_EVENT_TIMES["discussion"])
            start_time, end_time = patterns["times"]["discussion"]
            patterns["discussion_patterns"].append(
                {
                    "title": row.get("event type", "Discussion Section"),
                    "weekdays": weekdays,
                    "start_time": start_time,
                    "end_time": end_time,
                }
            )
        elif re.fullmatch(r"office hours?", event_type) or event_type.startswith("office hour "):
            patterns["office_hours"] = weekdays
            patterns["times"]["office_hours"] = read_row_time(row, DEFAULT_EVENT_TIMES["office_hours"])
            patterns["office_hour_patterns"].append(
                {
                    "title": row.get("event type", "Office Hours"),
                    "weekdays": weekdays,
                    "start_time": patterns["times"]["office_hours"][0],
                    "end_time": patterns["times"]["office_hours"][1],
                }
            )
    lab_rows = extract_table_after_heading(
        lab_path.read_text(encoding="utf-8").splitlines(),
        "Lab Meeting Pattern",
    )
    for row in lab_rows:
        event_type = row.get("event type", "").lower()
        weekdays = parse_weekday_list(row.get("weekday", "") or row.get("weekdays", ""))
        if weekdays and event_type in {"lab", "lab / project", "lab/project", "project"}:
            patterns["lab"] = weekdays
            patterns["times"]["lab"] = read_row_time(row, DEFAULT_EVENT_TIMES["lab"])
        elif weekdays and event_type in {"lab deliverable", "lab deliverables", "deliverable", "deliverables"}:
            patterns["lab_deliverable"] = weekdays
            patterns["times"]["lab_deliverable"] = read_row_time(row, DEFAULT_EVENT_TIMES["lab_deliverable"])
            patterns["lab_deliverable_week_offset"] = read_week_offset(
                row, DEFAULT_LAB_DELIVERABLE_WEEK_OFFSET, lab_path.name
            )
        elif weekdays and event_type in {"project deliverable", "project deliverables"}:
            patterns["project_deliverable"] = weekdays
            patterns["times"]["project_deliverable"] = read_row_time(row, DEFAULT_EVENT_TIMES["lab_deliverable"])
            patterns["project_deliverable_week_offset"] = read_week_offset(
                row, DEFAULT_LAB_DELIVERABLE_WEEK_OFFSET, lab_path.name
            )
        elif weekdays and event_type in {"tutorial hash", "tutorial hashes", "tutorial"}:
            patterns["tutorial_hash"] = weekdays
            patterns["times"]["tutorial_hash"] = read_row_time(row, DEFAULT_EVENT_TIMES["lab_deliverable"])
            patterns["tutorial_hash_week_offset"] = read_week_offset(
                row, DEFAULT_TUTORIAL_HASH_WEEK_OFFSET, lab_path.name
            )

    # The tutorial-hash and project deadlines share the lab deliverable weekday, time,
    # and offset unless their own rows override them.
    if patterns["tutorial_hash"] is None:
        patterns["tutorial_hash"] = patterns["lab_deliverable"]
        patterns["times"]["tutorial_hash"] = patterns["times"]["lab_deliverable"]
    if patterns["project_deliverable"] is None:
        patterns["project_deliverable"] = patterns["lab_deliverable"]
        patterns["times"]["project_deliverable"] = patterns["times"]["lab_deliverable"]
    if patterns["project_deliverable_week_offset"] is None:
        patterns["project_deliverable_week_offset"] = patterns["lab_deliverable_week_offset"]

    patterns["session_overrides"] = parse_session_overrides(lab_path, default_year)

    return patterns


def parse_important_dates_table(lines, current_year: int):
    rows = []
    headers = None
    for raw in lines:
        line = clean_text(raw)
        cells = split_markdown_table_row(line)
        if not cells:
            continue
        if is_markdown_separator(cells):
            continue
        if headers is None:
            headers = [cell.lower() for cell in cells]
            continue

        row = dict(zip(headers, cells))
        start_text = row.get("start date", "")
        end_text = row.get("end date", "")
        description = row.get("event", "")
        if not start_text or not description:
            continue

        start_date = parse_month_day(start_text, current_year)
        end_date = parse_month_day(end_text, current_year) if end_text else start_date
        rows.append({"start": start_date, "end": end_date, "description": description})

    return rows


def parse_important_dates(path: Path, default_year: int = DEFAULT_TERM_YEAR):
    if not path.exists():
        return []

    rows = []
    current_year = default_year
    lines = path.read_text(encoding="utf-8").splitlines()
    for raw in lines:
        line = clean_text(raw)
        if not line:
            continue

        term_match = re.match(r"^(?:Semester\s*:?\s*)?[A-Za-z]+\s+(\d{4})$", line, re.IGNORECASE)
        if term_match:
            current_year = int(term_match.group(1))
            break

    table_rows = parse_important_dates_table(lines, current_year)
    if table_rows:
        return table_rows

    for raw in lines:
        line = clean_text(raw)
        if not line:
            continue

        term_match = re.match(r"^(?:Semester\s*:?\s*)?[A-Za-z]+\s+(\d{4})$", line, re.IGNORECASE)
        if term_match:
            current_year = int(term_match.group(1))
            continue

        line = normalize_dash(line)
        m = re.match(r"^([A-Za-z]+\s+\d{1,2})(?:\s*-\s*([A-Za-z]+\s+)?(\d{1,2}))?\s+(.+)$", line)
        if not m:
            continue

        start_text, end_month, end_day, description = m.groups()
        start_date = parse_month_day(start_text, current_year)
        if end_day:
            month_name = end_month.strip() if end_month else calendar.month_name[start_date.month]
            end_date = parse_month_day(f"{month_name} {end_day}", current_year)
        else:
            end_date = start_date

        rows.append({"start": start_date, "end": end_date, "description": description})

    return rows


def important_dates_by_day(important_dates):
    by_day = defaultdict(list)
    for row in important_dates:
        current = row["start"]
        while current <= row["end"]:
            by_day[current].append(row["description"])
            current += timedelta(days=1)
    return by_day


def find_important_date(important_dates, pattern: str):
    regex = re.compile(pattern, re.IGNORECASE)
    for row in important_dates:
        if regex.search(row["description"]):
            return row
    return None


def term_bounds(important_dates, default_year: int = DEFAULT_TERM_YEAR):
    start = find_important_date(important_dates, r"Classes Begin")
    end = find_important_date(important_dates, r"Last Day of Classes")
    if not start or not end:
        return date(default_year, 9, 2), date(default_year, 12, 10)
    return start["start"], end["start"]


def class_suspended_dates(important_dates):
    suspended = set()
    for row in important_dates:
        description = row["description"].lower()
        if "classes suspended" in description or "thanksgiving recess" in description or "study period" in description:
            current = row["start"]
            while current <= row["end"]:
                suspended.add(current)
                current += timedelta(days=1)
    return suspended


def substitute_meeting_dates(important_dates):
    substitutes = set()
    for row in important_dates:
        if "substitute a monday schedule" in row["description"].lower():
            substitutes.add(row["start"])
    return substitutes


def build_class_meeting_dates(important_dates, lecture_weekdays, default_year: int = DEFAULT_TERM_YEAR):
    start, end = term_bounds(important_dates, default_year)
    suspended = class_suspended_dates(important_dates)
    substitutes = substitute_meeting_dates(important_dates)
    lecture_weekdays = set(lecture_weekdays)
    meetings = []
    current = start
    while current <= end:
        if (
            current in substitutes
            or current == end
            or (current.weekday() in lecture_weekdays and current not in suspended)
        ):
            meetings.append(current)
        current += timedelta(days=1)
    return meetings


def week_start_for_week(start: date, week: int) -> date:
    first_monday = start - timedelta(days=start.weekday())
    return first_monday + timedelta(weeks=week - 1)


def scheduled_weekday_date(
    term_start: date,
    week: int,
    weekday: int,
    suspended_dates: set[date],
    clamp_to_term_start: bool = True,
    shift_suspended: bool = True,
) -> date:
    candidate = week_start_for_week(term_start, week) + timedelta(days=weekday)
    if clamp_to_term_start and candidate < term_start:
        candidate = term_start
    while shift_suspended and candidate in suspended_dates:
        candidate += timedelta(days=1)
    return candidate


def course_week_for_date(term_start: date, event_date: date) -> int:
    first_monday = term_start - timedelta(days=term_start.weekday())
    return ((event_date - first_monday).days // 7) + 1


def nearby_important_dates(event_date: date, important_dates, window_days: int = 2):
    flags = []
    for row in important_dates:
        if not FLAGGABLE_IMPORTANT_DATE.search(row["description"]):
            continue
        if row["start"] <= event_date <= row["end"]:
            flags.append(row["description"])
            continue
        before = row["start"] - timedelta(days=window_days)
        after = row["end"] + timedelta(days=window_days)
        if before <= event_date <= after:
            flags.append(f"Near {row['description']}")
    return flags


def parse_learning_objectives(path: Path):
    objectives_by_code = {}
    objectives_by_tag = defaultdict(list)
    module_num = None

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip().replace("\u200b", "").replace("\ufeff", "")
        module_match = re.match(r"^#{1,6}\s+Module\s+(\d+):", line)
        if module_match:
            module_num = int(module_match.group(1))
            continue

        objective_match = re.match(r"^(\d+)\.\s+(.+)$", line)
        if not objective_match or module_num is None:
            continue

        lo_num = int(objective_match.group(1))
        body = objective_match.group(2)
        bold_groups = list(re.finditer(r"\*\*(.+?)\*\*", body))
        if not bold_groups:
            continue
        title_group = bold_groups[-1]
        title = re.sub(r"^\\?\[code\\?\]\s*", "", title_group.group(1), flags=re.IGNORECASE)
        title = clean_text(title).rstrip(".:")
        rest = clean_text(body[title_group.end() :].lstrip(".: "))
        if not title or not rest:
            continue

        code = objective_code(module_num, lo_num)
        objective = {
            "code": code,
            "label": f"{code}: {title}",
            "title": title,
            "description": re.sub(r"\s*\[[^\]]+\]\s*", " ", rest),
        }
        objectives_by_code[code] = objective

        tag_groups = re.findall(r"\[([^\]]+)\]", rest)
        for tag_group in tag_groups:
            for tag in re.split(r",|;", tag_group):
                tag = canonical_prerequisite_tag(tag)
                if tag:
                    objectives_by_tag[tag].append(code)
    return objectives_by_code, dict(objectives_by_tag)


def objective_code(module_num: int, lo_num: int):
    return f"M{module_num}.L{lo_num:02d}"


def canonical_prerequisite_tag(tag: str):
    compact_tag = re.sub(r"\s+", "", clean_text(tag)).upper()
    match = re.fullmatch(r"Q(?:UIZ)?(\d+)", compact_tag)
    if match:
        return f"QUIZ{int(match.group(1))}"

    match = re.fullmatch(r"L(?:AB)?(\d+)", compact_tag)
    if match:
        return f"LAB{int(match.group(1))}"

    match = re.fullmatch(r"P(?:ROJECT)?(\d+)", compact_tag)
    if match:
        return f"PROJECT{int(match.group(1))}"

    return ""


def objective_code_from_text(text: str):
    match = re.search(r"M\s*(\d+)\s*\.\s*L\s*0?(\d+)", text, re.IGNORECASE)
    if match:
        return objective_code(int(match.group(1)), int(match.group(2)))

    match = re.search(r"M\s*(\d+)\s*,\s*L(?:O|0)?\s*0?(\d+)", text, re.IGNORECASE)
    if match:
        return objective_code(int(match.group(1)), int(match.group(2)))

    return None


def objective_lookup_by_text(objectives_by_code):
    lookup = {}
    for code, objective in objectives_by_code.items():
        lookup[normalize_objective_text(objective["title"])] = code
        lookup[normalize_objective_text(objective["description"])] = code
    return lookup


def match_objective_text(text: str, lookup):
    key = normalize_objective_text(text)
    if key in lookup:
        return lookup[key]
    for objective_text, code in lookup.items():
        if key and (key in objective_text or objective_text in key):
            return code
    return None


def lab_prerequisite_tag(title: str):
    lab_match = re.match(r"Lab\s+(\d+)", title)
    if lab_match:
        return f"LAB{int(lab_match.group(1))}"
    project_match = re.match(r"(?:P|Project\s*)(\d+)", title, re.IGNORECASE)
    if project_match:
        return f"PROJECT{int(project_match.group(1))}"
    return ""


def prerequisite_flags(event_label: str, event_date, prerequisite_codes, taught_objectives, objectives_by_code):
    if not prerequisite_codes:
        return [f"Missing prerequisite metadata: add learning-objective tags for {event_label}"]
    if event_date is None:
        return [f"Cannot check prerequisites for {event_label}: no scheduled date"]

    flags = []
    for code in prerequisite_codes:
        taught = taught_objectives.get(code)
        objective = objectives_by_code.get(code, {"label": code})
        if not taught:
            flags.append(f"Prerequisite not found in lectures: {objective['label']}")
            continue
        if taught["date"] is None:
            flags.append(
                f"Prerequisite not yet covered: {objective['label']} "
                f"(first covered {taught['label']})"
            )
        elif taught["date"] == event_date:
            flags.append(
                f"Prerequisite may be same-day: {objective['label']} "
                f"(first covered {taught['label']})"
            )
        elif taught["date"] > event_date:
            flags.append(
                f"Prerequisite not yet covered: {objective['label']} "
                f"(first covered {taught['label']})"
            )
    return flags


def annotate_prerequisite_flags(
    lecture_rows,
    lab_rows,
    objectives_by_code,
    objectives_by_tag,
    important_dates,
    meeting_patterns,
    default_year: int = DEFAULT_TERM_YEAR,
):
    objective_lookup = objective_lookup_by_text(objectives_by_code)
    taught_objectives = {}
    for row in lecture_rows:
        if row.get("kind") != "lecture":
            continue
        for code in row.get("objective_codes", []):
            if code not in taught_objectives:
                taught_objectives[code] = {"date": row.get("date"), "label": row["label"]}

    for row in lecture_rows:
        if row.get("kind") != "quiz":
            continue
        tag = f"QUIZ{row['lecture_num']}"
        row["prerequisite_codes"] = objectives_by_tag.get(tag, [])
        row.setdefault("flags", []).extend(
            prerequisite_flags(row["label"], row.get("date"), row["prerequisite_codes"], taught_objectives, objectives_by_code)
        )

    term_start, _ = term_bounds(important_dates, default_year)
    suspended = class_suspended_dates(important_dates)
    lab_weekday = meeting_patterns["lab"][0]
    session_overrides = meeting_patterns.get("session_overrides", {})
    for lab in lab_rows:
        override = session_overrides.get(normalize_session_key(lab["title"]), {})
        if lab["week"] is not None or override.get("date"):
            lab_date = override.get("date") or scheduled_weekday_date(
                term_start, lab["week"], lab_weekday, suspended
            )
            lab["date"] = lab_date
            lab.setdefault("flags", []).extend(nearby_important_dates(lab_date, important_dates))
        tag = lab_prerequisite_tag(lab["title"])
        prerequisite_codes = list(objectives_by_tag.get(tag, []))
        if not prerequisite_codes and lab.get("objective_list"):
            prerequisite_codes = [
                code
                for code in (match_objective_text(objective, objective_lookup) for objective in lab["objective_list"])
                if code
            ]
        lab["prerequisite_codes"] = prerequisite_codes
        lab.setdefault("flags", []).extend(
            prerequisite_flags(lab["title"], lab.get("date"), prerequisite_codes, taught_objectives, objectives_by_code)
        )


def week_for_lecture_num(num: int) -> int:
    # Fallback grouping for lecture blocks.
    return ((num - 1) // 3) + 1


def parse_quiz_schedule(path: Path):
    if not path.exists():
        return []

    rows = extract_table_after_heading(
        path.read_text(encoding="utf-8").splitlines(),
        "Quiz Schedule",
    )
    quiz_rows = []
    for row in rows:
        quiz = clean_text(row.get("quiz", ""))
        after_lecture = clean_text(row.get("after lecture", ""))
        if not quiz or not after_lecture:
            continue
        quiz_match = re.search(r"(\d+)", quiz)
        lecture_match = re.search(r"(\d+)", after_lecture)
        if not quiz_match or not lecture_match:
            continue
        status = clean_text(row.get("status", ""))
        notes = clean_text(row.get("notes", ""))
        quiz_rows.append(
            {
                "label": f"Quiz {int(quiz_match.group(1))}",
                "quiz_num": int(quiz_match.group(1)),
                "after_lecture": int(lecture_match.group(1)),
                "status": status,
                "notes": notes,
            }
        )
    return sorted(quiz_rows, key=lambda row: (row["after_lecture"], row["quiz_num"]))


def parse_additional_assessment_schedule(path: Path):
    if not path.exists():
        return []

    rows = extract_table_after_heading(
        path.read_text(encoding="utf-8").splitlines(),
        "Additional Assessment Schedule",
    )
    assessments = []
    for row in rows:
        title = clean_text(row.get("assessment", "") or row.get("event", "") or row.get("title", ""))
        timing = clean_text(row.get("timing", ""))
        if not title or not timing:
            continue
        assessments.append(
            {
                "label": title,
                "timing": timing,
                "status": clean_text(row.get("status", "")),
                "notes": clean_text(row.get("notes", "")),
                "kind": "assessment",
                "flags": [],
            }
        )
    return assessments


def parse_homework_schedule(path: Path):
    if not path.exists():
        return []

    rows = extract_table_after_heading(
        path.read_text(encoding="utf-8").splitlines(),
        "Homework Schedule",
    )
    homework_rows = []
    for index, row in enumerate(rows, start=1):
        week_match = re.search(r"\d+", row.get("week", ""))
        weekdays = parse_weekday_list(row.get("weekday", "") or row.get("weekdays", ""))
        if not week_match or not weekdays:
            continue

        title = clean_text(row.get("homework", "") or row.get("title", "") or row.get("event type", ""))
        details = clean_text(row.get("details", "") or row.get("description", ""))
        end_time = normalize_event_time(row.get("end time", "")) or DEFAULT_EVENT_TIMES["homework"][1]
        homework_rows.append(
            {
                "week": int(week_match.group(0)),
                "weekday": weekdays[0],
                "title": title or f"Homework {index}",
                "details": details or "Weekly homework component.",
                "start_time": "",
                "end_time": end_time,
            }
        )

    return homework_rows


def parse_exception_events(path: Path, default_year: int = DEFAULT_TERM_YEAR):
    if not path.exists():
        return []

    rows = extract_table_after_heading(
        path.read_text(encoding="utf-8").splitlines(),
        "Exceptions",
    )
    exception_rows = []
    for row in rows:
        date_text = clean_text(row.get("date", ""))
        title = clean_text(row.get("title", "") or row.get("event", ""))
        if not date_text or not title:
            continue

        event_type = clean_text(row.get("event type", "") or row.get("kind", "") or "Additional Event")
        kind = re.sub(r"[^a-z0-9]+", "-", event_type.lower()).strip("-") or "additional-event"
        details = clean_text(row.get("details", "") or row.get("description", ""))
        schedule_text = clean_text(row.get("include in schedule", "") or row.get("schedule", "")).lower()
        include_in_schedule = schedule_text not in {"no", "n", "false", "0"}
        exception_rows.append(
            {
                "date": parse_schedule_date(date_text, default_year),
                "kind": kind,
                "event_type": event_type,
                "title": title,
                "details": details,
                "start_time": normalize_event_time(row.get("start time", "")),
                "end_time": normalize_event_time(row.get("end time", "")),
                "include_in_schedule": include_in_schedule,
                "schedule_note": clean_text(row.get("schedule note", "")),
            }
        )

    return sorted(exception_rows, key=lambda item: (item["date"], item["title"]))


def parse_lecture_summary(path: Path, quiz_schedule=None):
    text = path.read_text(encoding="utf-8")
    sections = {}
    current = None
    current_heading = None

    for raw in text.splitlines():
        line = raw.rstrip()
        if re.match(r"^###\s+Lecture\s+.+", line):
            if current is not None and current_heading is not None:
                sections[current_heading] = current
            current_heading = line.split("###", 1)[1].strip()
            current = []
        elif current is not None:
            current.append(line)

    if current is not None and current_heading is not None:
        sections[current_heading] = current

    lecture_rows = []
    for heading, block in sections.items():
        m = re.match(r"^Lecture\s+(\d+)", heading)
        if not m:
            continue
        num = int(m.group(1))

        topic = ""
        objective_codes = []
        for line in block:
            if "**Topic:**" in line:
                topic = line.split("**Topic:**", 1)[1].strip()
            code = objective_code_from_text(line)
            if code:
                objective_codes.append(code)

        lecture_rows.append(
            {
                "label": heading,
                "lecture_num": num,
                "week": None,
                "topic": topic,
                "objective_codes": objective_codes,
                "kind": "lecture",
                "flags": [],
            }
        )

    quiz_schedule = quiz_schedule or []
    quizzes_by_anchor = defaultdict(list)
    for quiz in quiz_schedule:
        quizzes_by_anchor[quiz["after_lecture"]].append(quiz)

    sequenced_rows = []
    for row in sorted(lecture_rows, key=lambda item: item["lecture_num"]):
        sequenced_rows.append(row)
        for quiz in quizzes_by_anchor.get(row["lecture_num"], []):
            details = []
            if quiz["status"]:
                details.append(quiz["status"])
            if quiz["notes"]:
                details.append(quiz["notes"])
            sequenced_rows.append(
                {
                    "label": quiz["label"],
                    "lecture_num": quiz["quiz_num"],
                    "after_lecture": quiz["after_lecture"],
                    "week": None,
                    "topic": "; ".join(details) if details else "Quiz in the scheduled course window.",
                    "kind": "quiz",
                    "flags": [],
                }
            )

    return sequenced_rows


def assign_course_dates(lecture_rows, important_dates, meeting_patterns, default_year: int = DEFAULT_TERM_YEAR):
    class_dates = build_class_meeting_dates(important_dates, meeting_patterns["lecture"], default_year)
    term_start, _ = term_bounds(important_dates, default_year)
    for row, meeting_date in zip(lecture_rows, class_dates):
        row["date"] = meeting_date
        row["week"] = course_week_for_date(term_start, meeting_date)
        row["flags"] = nearby_important_dates(meeting_date, important_dates)
    for row in lecture_rows[len(class_dates) :]:
        row["date"] = None
        row["flags"] = ["No available class meeting date"]
    return lecture_rows


def assign_additional_assessment_dates(
    assessment_rows,
    lecture_rows,
    important_dates,
    meeting_patterns,
    default_year: int = DEFAULT_TERM_YEAR,
):
    class_dates = build_class_meeting_dates(
        important_dates,
        meeting_patterns["lecture"],
        default_year,
    )
    last_lecture_date = max(class_dates) if class_dates else None
    final_exam_start = find_important_date(important_dates, r"Final Exams Begin")
    final_exam_end = find_important_date(important_dates, r"Final Exams End")
    term_start, _ = term_bounds(important_dates, default_year)

    for row in assessment_rows:
        timing = re.sub(r"\s+", " ", row["timing"]).strip().lower()
        if timing == "last lecture":
            if last_lecture_date is None:
                raise ValueError("Cannot schedule 'Last Lecture': no class meeting dates were generated.")
            row["date"] = last_lecture_date
            row["end_date"] = last_lecture_date
            row["week"] = course_week_for_date(term_start, last_lecture_date)
            row["uses_lecture_time"] = True
        elif timing == "final exam period":
            if final_exam_start is None or final_exam_end is None:
                raise ValueError(
                    "Cannot schedule 'Final Exam Period': important_dates.md must include "
                    "'Final Exams Begin' and 'Final Exams End'."
                )
            row["date"] = final_exam_start["start"]
            row["end_date"] = final_exam_end["end"]
            row["week"] = course_week_for_date(term_start, row["date"])
            row["uses_lecture_time"] = False
        else:
            raise ValueError(
                f"Unsupported additional-assessment timing '{row['timing']}'. "
                "Use 'Last Lecture' or 'Final Exam Period'."
            )

        detail_parts = [row["status"], row["notes"]]
        row["details"] = "; ".join(part for part in detail_parts if part)

    return assessment_rows


def split_combined_lab_titles(title: str):
    match = re.fullmatch(r"(P(?:roject)?\d+)-(\d+)/(?:P(?:roject)?\d+-)?(\d+)", title, re.IGNORECASE)
    if not match:
        return [title]

    project_prefix = match.group(1)
    return [f"{project_prefix}-{match.group(2)}", f"{project_prefix}-{match.group(3)}"]


LAB_FIELD_ALIASES = {
    "week": "week",
    "lecture anchor": "lecture_anchor",
    "purpose": "purpose",
    "primary objectives": "objectives",
    "primary objectives supported": "objectives",
    "pre lab activity": "pre_lab",
    "pre-lab activity": "pre_lab",
    "in lab activity": "in_lab",
    "in-lab activity": "in_lab",
    "post lab activity": "post_lab",
    "post-lab activity": "post_lab",
    "deliverables": "deliverables",
}


def canonical_lab_field(label: str):
    key = label.lower().replace(":", "")
    key = re.sub(r"[^a-z0-9-]+", " ", key)
    key = clean_text(key)
    return LAB_FIELD_ALIASES.get(key, "")


def parse_lab_field_line(line: str):
    match = re.match(r"^-?\s*\*\*([^*]+?):\*\*\s*(.*)$", line)
    if match:
        return canonical_lab_field(match.group(1)), clean_text(match.group(2))

    match = re.match(r"^\*\*([^*]+)\*\*\s*$", line)
    if match:
        return canonical_lab_field(match.group(1)), ""

    return "", ""


def parse_lab_summary(path: Path):
    text = path.read_text(encoding="utf-8")
    sections = {}
    current = None
    current_heading = None

    for raw in text.splitlines():
        line = raw.rstrip()
        if re.match(r"^###\s+(Lab\s+\d+|P\d+(?:-\d+|/\d+)*|Project\s*\d+(?:-\d+|/\d+)*.*)", line):
            if current is not None and current_heading is not None:
                sections[current_heading] = current
            current_heading = line.split("###", 1)[1].strip()
            current = []
        elif current is not None:
            current.append(line)

    if current is not None and current_heading is not None:
        sections[current_heading] = current

    lab_rows = []
    for heading, block in sections.items():
        # Match headings like: Lab 1: R Intro, Project1-1: Project 1 Logistics, etc.
        title = heading.split(":", 1)[0].strip()

        fields = {"week": "", "lecture_anchor": "", "purpose": "", "objectives": [], "deliverables": []}
        current_field = ""
        purpose_lines = []
        for line in block:
            stripped = line.strip()
            if not stripped:
                continue

            field, value = parse_lab_field_line(stripped)
            if field:
                current_field = field
                if field in {"objectives", "deliverables"}:
                    if value:
                        fields[field].append(value)
                elif field in fields:
                    fields[field] = value
                continue

            if stripped.startswith("- "):
                value = clean_text(stripped[2:])
                if current_field in {"objectives", "deliverables"}:
                    fields[current_field].append(value)
                elif current_field == "purpose":
                    purpose_lines.append(value)

        if not fields["purpose"] and purpose_lines:
            fields["purpose"] = " ".join(purpose_lines)

        row = {
            "heading": heading,
            "title": title,
            "purpose": fields["purpose"],
            "lecture_anchor": fields["lecture_anchor"],
            "week": int(fields["week"]) if str(fields["week"]).isdigit() else None,
            "objectives": " | ".join(fields["objectives"]),
            "objective_list": fields["objectives"],
            "deliverables": " | ".join(fields["deliverables"]),
            "flags": [],
        }

        for split_title in split_combined_lab_titles(title):
            lab_rows.append({**row, "title": split_title})

    next_week = 1
    for row in lab_rows:
        if row["week"] is None:
            row["week"] = next_week
        next_week = row["week"] + 1

    return lab_rows


def build_week_table(lecture_rows, lab_rows, assessment_rows=None, exception_rows=None, term_start: date | None = None):
    assessment_rows = assessment_rows or []
    exception_rows = exception_rows or []
    # group lectures by week
    week_to_lectures = defaultdict(list)
    for row in lecture_rows:
        week_to_lectures[row["week"]].append(row)

    # build schedule rows for all relevant weeks, including project sessions
    all_weeks = set(week_to_lectures.keys())
    for lab in lab_rows:
        if lab["week"] is not None:
            all_weeks.add(lab["week"])
    for assessment in assessment_rows:
        if assessment.get("week") is not None:
            all_weeks.add(assessment["week"])

    week_to_exceptions = defaultdict(list)
    for event in exception_rows:
        if not event.get("include_in_schedule"):
            continue
        week = course_week_for_date(term_start, event["date"]) if term_start else None
        if week is None:
            continue
        label = event.get("schedule_note") or event["title"]
        if event.get("details") and not event.get("schedule_note"):
            label = f"{label}: {event['details']}"
        week_to_exceptions[week].append(label)
    all_weeks.update(week_to_exceptions.keys())

    rows = []
    for week in sorted(all_weeks):
        lectures = week_to_lectures.get(week, [])
        lecture_labels = ", ".join([r["label"] for r in lectures])
        lecture_topics = "; ".join(
            [f"{r['label']}: {r['topic']}" if r["topic"] else r["label"] for r in lectures]
        )
        flags = []
        for row in lectures:
            for flag in row.get("flags", []):
                flags.append(f"{row['label']}: {flag}")
        labs = []
        lab_deliverables = []
        for lab in lab_rows:
            if lab["week"] == week:
                anchor = lab["lecture_anchor"]
                labs.append(f"{lab['title']} ({anchor})" if anchor else lab["title"])
                if lab["deliverables"]:
                    lab_deliverables.append(f"{lab['title']}: {lab['deliverables']}")
                for flag in lab.get("flags", []):
                    flags.append(f"{lab['title']}: {flag}")
        assessments = []
        for assessment in assessment_rows:
            if assessment.get("week") == week:
                details = assessment.get("details", "")
                assessments.append(
                    f"{assessment['label']} ({details})" if details else assessment["label"]
                )

        rows.append(
            {
                "Week": week,
                "Lecture #": lecture_labels,
                "Lecture Topics": lecture_topics,
                "Labs": " | ".join(labs),
                "Lab Deliverables": " | ".join(lab_deliverables),
                "Assessments": " | ".join(assessments),
                "Additional Events": " | ".join(week_to_exceptions.get(week, [])),
                "Instructor Flags": " | ".join(dict.fromkeys(flags)),
            }
        )

    return pd.DataFrame(rows)


def write_schedule_table(df: pd.DataFrame, xlsx_path: Path, sheet_name: str):
    if xlsx_path.exists():
        wb = load_workbook(xlsx_path)
        if sheet_name in wb.sheetnames:
            ws = wb[sheet_name]
            wb.remove(ws)
        ws = wb.create_sheet(title=sheet_name)
    else:
        wb = Workbook()
        ws = wb.active
        ws.title = sheet_name

    # write headers
    headers = list(df.columns)
    ws.append(headers)

    # write values
    for _, row in df.iterrows():
        ws.append([row[col] for col in headers])

    # style header row
    header_fill = PatternFill("solid", fgColor="D9EAF7")
    header_font = Font(bold=True)
    for cell in ws[1]:
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center")

    # auto-size columns
    for col in ws.columns:
        max_len = 0
        column = col[0].column_letter
        for cell in col:
            try:
                if cell.value is not None:
                    max_len = max(max_len, len(str(cell.value)))
            except Exception:
                pass
        ws.column_dimensions[column].width = min(max_len + 3, 80)

    wb.save(xlsx_path)


def write_markdown_table(df: pd.DataFrame, md_path: Path, include_instructor_flags: bool = True):
    output_df = df
    if not include_instructor_flags and "Instructor Flags" in output_df.columns:
        output_df = output_df.drop(columns=["Instructor Flags"])

    headers = list(output_df.columns)
    lines = [
        "# Weekly Schedule",
        "",
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]

    for _, row in output_df.iterrows():
        values = [str(row[col]).replace("|", "\\|") for col in headers]
        lines.append("| " + " | ".join(values) + " |")

    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def event_card(kind: str, title: str, details: str = "", meta: str = "", time_range: str = "") -> str:
    lines = [f'<article class="calendar-event calendar-event--{kind}">']
    lines.append(f'<div class="calendar-event__kind">{escape(kind.replace("-", " ").title())}</div>')
    lines.append(f'<h3>{escape(title)}</h3>')
    if time_range:
        lines.append(f'<p class="calendar-event__time">{escape(time_range)}</p>')
    if details:
        lines.append(f"<p>{escape(details)}</p>")
    if meta:
        lines.append(f'<p class="calendar-event__meta">{escape(meta)}</p>')
    lines.append("</article>")
    return "\n".join(lines)


def ics_escape(text: str) -> str:
    return (
        text.replace("\\", "\\\\")
        .replace(";", "\\;")
        .replace(",", "\\,")
        .replace("\n", "\\n")
    )


def fold_ics_line(line: str) -> list[str]:
    if len(line) <= 75:
        return [line]
    folded = [line[:75]]
    rest = line[75:]
    while rest:
        folded.append(" " + rest[:74])
        rest = rest[74:]
    return folded


def write_ics_calendar(events, ics_path: Path, config: CourseSiteConfig):
    lines = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        f"PRODID:-//{config.course_code}//Course Calendar//EN",
        "CALSCALE:GREGORIAN",
        "METHOD:PUBLISH",
        f"X-WR-CALNAME:{config.course_title} Course Calendar",
        f"X-WR-TIMEZONE:{config.local_timezone}",
    ]

    for event_date in sorted(events):
        for index, item in enumerate(events[event_date], start=1):
            title = item["title"]
            details = item.get("details", "")
            meta = item.get("meta", "")
            description = details if not meta else f"{details}\n{meta}" if details else meta
            uid_text = re.sub(r"[^A-Za-z0-9]+", "-", f"{event_date}-{index}-{title}").strip("-")
            event_lines = [
                "BEGIN:VEVENT",
                f"UID:{uid_text}@{config.course_code.lower()}-course-calendar",
                "DTSTAMP:20260101T000000Z",
            ]
            start_time = item.get("start_time", "")
            end_time = item.get("end_time", "")
            if start_time and end_time:
                start_dt = time_for_ics(event_date, start_time)
                end_dt = time_for_ics(event_date, end_time)
                event_lines.extend(
                    [
                        f"DTSTART;TZID={config.local_timezone}:{start_dt:%Y%m%dT%H%M%S}",
                        f"DTEND;TZID={config.local_timezone}:{end_dt:%Y%m%dT%H%M%S}",
                    ]
                )
            elif end_time:
                due_dt = time_for_ics(event_date, end_time)
                event_lines.append(f"DTSTART;TZID={config.local_timezone}:{due_dt:%Y%m%dT%H%M%S}")
            elif start_time:
                start_dt = time_for_ics(event_date, start_time)
                event_lines.append(f"DTSTART;TZID={config.local_timezone}:{start_dt:%Y%m%dT%H%M%S}")
            else:
                next_day = item.get("end_date", event_date) + timedelta(days=1)
                event_lines.extend(
                    [
                        f"DTSTART;VALUE=DATE:{event_date:%Y%m%d}",
                        f"DTEND;VALUE=DATE:{next_day:%Y%m%d}",
                    ]
                )
            event_lines.append(f"SUMMARY:{ics_escape(title)}")
            if description:
                event_lines.append(f"DESCRIPTION:{ics_escape(description)}")
            event_lines.append("END:VEVENT")
            for line in event_lines:
                lines.extend(fold_ics_line(line))

    lines.append("END:VCALENDAR")
    ics_path.write_text("\r\n".join(lines) + "\r\n", encoding="utf-8")


def build_calendar_events(
    lecture_rows,
    lab_rows,
    homework_rows,
    assessment_rows,
    exception_rows,
    important_dates,
    meeting_patterns,
    include_instructor_flags: bool = True,
    default_year: int = DEFAULT_TERM_YEAR,
):
    events = defaultdict(list)
    important_by_day = important_dates_by_day(important_dates)
    term_start, term_end = term_bounds(important_dates, default_year)
    suspended = class_suspended_dates(important_dates)
    lab_weekday = meeting_patterns["lab"][0]
    lab_deliverable_weekday = meeting_patterns["lab_deliverable"][0]
    lab_deliverable_week_offset = meeting_patterns.get(
        "lab_deliverable_week_offset", DEFAULT_LAB_DELIVERABLE_WEEK_OFFSET
    )
    tutorial_hash_weekday = (meeting_patterns.get("tutorial_hash") or meeting_patterns["lab_deliverable"])[0]
    tutorial_hash_week_offset = meeting_patterns.get(
        "tutorial_hash_week_offset", DEFAULT_TUTORIAL_HASH_WEEK_OFFSET
    )
    project_deliverable_weekday = (
        meeting_patterns.get("project_deliverable") or meeting_patterns["lab_deliverable"]
    )[0]
    project_deliverable_week_offset = (
        meeting_patterns.get("project_deliverable_week_offset")
        if meeting_patterns.get("project_deliverable_week_offset") is not None
        else lab_deliverable_week_offset
    )
    session_overrides = meeting_patterns.get("session_overrides", {})

    for row in lecture_rows:
        meeting_date = row.get("date")
        if meeting_date is None:
            continue
        label = row["label"]
        kind = row.get("kind", "quiz" if label.startswith("Quiz") else "lecture")
        details = row["topic"] or "Quiz in the scheduled course window."
        meta = " | ".join(row.get("flags", [])) if include_instructor_flags else ""
        start_time, end_time = event_time_range(meeting_patterns, "lecture")
        events[meeting_date].append(
            {
                "kind": kind,
                "title": label,
                "details": details,
                "meta": meta,
                "start_time": start_time,
                "end_time": end_time,
            }
        )

    for lab in lab_rows:
        override = session_overrides.get(normalize_session_key(lab["title"]), {})
        if lab["week"] is None and not override.get("date"):
            continue
        lab_date = override.get("date") or lab.get("date") or scheduled_weekday_date(
            term_start, lab["week"], lab_weekday, suspended
        )
        lab["date"] = lab_date
        existing_flags = list(lab.get("flags", []))
        lab["flags"] = list(dict.fromkeys(existing_flags + nearby_important_dates(lab_date, important_dates)))
        kind = "lab"
        start_time, end_time = event_time_range(meeting_patterns, "lab")
        meta_parts = []
        if lab["lecture_anchor"]:
            meta_parts.append(f"Anchor: {lab['lecture_anchor']}")
        events[lab_date].append(
            {
                "kind": kind,
                "title": lab["title"],
                "details": "",
                "meta": " | ".join(meta_parts),
                "start_time": start_time,
                "end_time": end_time,
            }
        )

        # The tutorial hash is due before its own lab, the rest of the deliverables
        # after it, so they become two deadlines. Offsets and per-session dates are
        # instructor-editable in instructor_inputs/Lab_schedules.md.
        tutorial_items, deliverable_items = split_tutorial_deliverables(lab["deliverables"])

        def deadline(override_key, week_offset, weekday):
            pinned = override.get(override_key)
            if pinned is not None:
                return pinned
            if lab["week"] is None:
                return None
            return scheduled_weekday_date(
                term_start, lab["week"] + week_offset, weekday, suspended
            )

        if tutorial_items:
            tutorial_date = deadline("tutorial_date", tutorial_hash_week_offset, tutorial_hash_weekday)
            if tutorial_date is not None and term_start <= tutorial_date <= term_end:
                start_time, end_time = event_time_range(meeting_patterns, "tutorial_hash")
                events[tutorial_date].append(
                    {
                        "kind": "lab-deliverable",
                        "title": f"{lab['title']} Tutorial Hash Due",
                        "details": " | ".join(tutorial_items),
                        "start_time": start_time,
                        "end_time": end_time,
                    }
                )

        if deliverable_items:
            # Project deliverables keep their own weekday and offset, so changing when
            # lab worksheets are due does not move the project milestones with them.
            is_project = bool(re.match(r"project", lab["title"], re.IGNORECASE))
            deliverable_key = "project_deliverable" if is_project else "lab_deliverable"
            deliverable_date = deadline(
                "deliverable_date",
                project_deliverable_week_offset if is_project else lab_deliverable_week_offset,
                project_deliverable_weekday if is_project else lab_deliverable_weekday,
            )
            if deliverable_date is not None and term_start <= deliverable_date <= term_end:
                start_time, end_time = event_time_range(meeting_patterns, deliverable_key)
                events[deliverable_date].append(
                    {
                        "kind": "lab-deliverable",
                        "title": f"{lab['title']} Deliverables Due",
                        "details": " | ".join(deliverable_items),
                        "start_time": start_time,
                        "end_time": end_time,
                    }
                )

    max_week = max([row["week"] for row in lecture_rows] + [row["week"] for row in lab_rows if row["week"]])
    for week in range(1, max_week + 1):
        for discussion in meeting_patterns["discussion_patterns"]:
            for weekday in discussion["weekdays"]:
                discussion_date = scheduled_weekday_date(term_start, week, weekday, suspended, clamp_to_term_start=False)
                if term_start <= discussion_date <= term_end:
                    events[discussion_date].append(
                        {
                            "kind": "discussion",
                            "title": discussion["title"],
                            "details": "",
                            "start_time": discussion["start_time"],
                            "end_time": discussion["end_time"],
                        }
                    )
        for office_hour in meeting_patterns["office_hour_patterns"]:
            for weekday in office_hour["weekdays"]:
                office_hours_date = scheduled_weekday_date(
                    term_start,
                    week,
                    weekday,
                    suspended,
                    clamp_to_term_start=False,
                    shift_suspended=False,
                )
                if term_start <= office_hours_date <= term_end and office_hours_date not in suspended:
                    events[office_hours_date].append(
                        {
                            "kind": "office-hours",
                            "title": office_hour["title"],
                            "details": "",
                            "start_time": office_hour["start_time"],
                            "end_time": office_hour["end_time"],
                        }
                    )

    for homework in homework_rows:
        homework_date = scheduled_weekday_date(
            term_start,
            homework["week"],
            homework["weekday"],
            suspended,
            clamp_to_term_start=False,
        )
        if term_start <= homework_date <= term_end:
            events[homework_date].append(
                {
                    "kind": "homework",
                    "title": homework["title"],
                    "details": homework["details"],
                    "start_time": homework["start_time"],
                    "end_time": homework["end_time"],
                }
            )

    for assessment in assessment_rows:
        assessment_date = assessment.get("date")
        if assessment_date is None:
            continue
        start_time = ""
        end_time = ""
        if assessment.get("uses_lecture_time"):
            start_time, end_time = event_time_range(meeting_patterns, "lecture")
        end_date = assessment.get("end_date", assessment_date)
        date_range = ""
        if end_date > assessment_date:
            date_range = (
                f"{assessment_date.strftime('%B')} {assessment_date.day}–"
                f"{end_date.strftime('%B')} {end_date.day}, {end_date.year}"
            )
        details = assessment.get("details", "")
        meta_parts = [assessment["timing"], date_range]
        events[assessment_date].append(
            {
                "kind": "assessment",
                "title": assessment["label"],
                "details": details,
                "meta": " | ".join(part for part in meta_parts if part),
                "start_time": start_time,
                "end_time": end_time,
                "end_date": end_date,
            }
        )

    for event in exception_rows:
        events[event["date"]].append(
            {
                "kind": event["kind"],
                "title": event["title"],
                "details": event["details"],
                "start_time": event["start_time"],
                "end_time": event["end_time"],
            }
        )

    for day, descriptions in important_by_day.items():
        for description in descriptions:
            events[day].insert(
                0,
                {
                    "kind": "important-date",
                    "title": "Academic Calendar",
                    "details": description,
                },
            )

    return events


def month_grid_dates(year: int, month: int):
    first = date(year, month, 1)
    days_since_sunday = (first.weekday() + 1) % 7
    start = first - timedelta(days=days_since_sunday)
    return [start + timedelta(days=i) for i in range(42)]


def months_to_render(important_dates, exception_rows=None, default_year: int = DEFAULT_TERM_YEAR):
    exception_rows = exception_rows or []
    term_start, term_end = term_bounds(important_dates, default_year)
    latest = term_end
    for row in important_dates:
        latest = max(latest, row["end"])
    for row in exception_rows:
        latest = max(latest, row["date"])

    months = []
    current = date(term_start.year, term_start.month, 1)
    final = date(latest.year, latest.month, 1)
    while current <= final:
        months.append(current)
        if current.month == 12:
            current = date(current.year + 1, 1, 1)
        else:
            current = date(current.year, current.month + 1, 1)
    return months


def write_calendar_markdown(
    lecture_rows,
    lab_rows,
    homework_rows,
    assessment_rows,
    exception_rows,
    important_dates,
    meeting_patterns,
    md_path: Path,
    include_instructor_flags: bool = True,
    default_year: int = DEFAULT_TERM_YEAR,
):
    events = build_calendar_events(
        lecture_rows,
        lab_rows,
        homework_rows,
        assessment_rows,
        exception_rows,
        important_dates,
        meeting_patterns,
        include_instructor_flags,
        default_year,
    )
    class_dates = build_class_meeting_dates(important_dates, meeting_patterns["lecture"], default_year)
    term_start, term_end = term_bounds(important_dates, default_year)
    term_start_label = f"{term_start.strftime('%B')} {term_start.day}, {term_start.year}"
    term_end_label = f"{term_end.strftime('%B')} {term_end.day}, {term_end.year}"
    lines = [
        "# Calendar View",
        "",
        '<div class="calendar-note">',
        f"This month view is generated from course summaries, `instructor_inputs/important_dates.md`, and one-off events in `instructor_inputs/Exception_schedules.md`. It assigns lectures and quizzes to class-meeting dates from {term_start_label} through {term_end_label}; exact rooms, section times, and office-hour locations should follow the current syllabus.",
        "</div>",
        "",
        '<details class="calendar-download-menu">',
        '<summary class="calendar-download-trigger">Download Calendar</summary>',
        '<div class="calendar-download-options">',
        '<a class="calendar-download-option" href="../course_calendar.ics" download>Google Calendar</a>',
        '<a class="calendar-download-option" href="../course_calendar.ics" download>Apple Calendar</a>',
        '<a class="calendar-download-option" href="../course_calendar.ics" download>Outlook</a>',
        "</div>",
        "</details>",
        "",
    ]

    if len(lecture_rows) > len(class_dates):
        missing = len(lecture_rows) - len(class_dates)
        lines.extend(
            [
                '<div class="calendar-warning">',
                f"{missing} lecture/quiz item(s) could not be assigned because there are not enough class-meeting dates.",
                "</div>",
                "",
            ]
        )

    for month_start in months_to_render(important_dates, exception_rows, default_year):
        month = month_start.month
        year = month_start.year
        month_name = calendar.month_name[month]
        lines.append(f'<section class="calendar-month" aria-labelledby="{month_name.lower()}-{year}">')
        lines.append(f'<h2 id="{month_name.lower()}-{year}">{month_name} {year}</h2>')
        lines.append('<div class="calendar-month-grid">')
        for weekday in CALENDAR_WEEKDAYS:
            lines.append(f'<div class="calendar-weekday">{escape(weekday)}</div>')

        for day in month_grid_dates(year, month):
            classes = ["calendar-date"]
            if day.month != month:
                classes.append("calendar-date--outside")
            if day < term_start or day > term_end:
                classes.append("calendar-date--term-edge")
            lines.append(f'<section class="{" ".join(classes)}">')
            lines.append(f'<div class="calendar-date__number">{day.day}</div>')
            day_events = events.get(day, []) if day.month == month else []
            for item in day_events:
                lines.append(
                    event_card(
                        item["kind"],
                        item["title"],
                        item.get("details", ""),
                        item.get("meta", ""),
                        format_time_range(item.get("start_time", ""), item.get("end_time", "")),
                    )
                )
            if not day_events and day.month == month:
                lines.append('<p class="calendar-empty">No events</p>')
            lines.append("</section>")
        lines.append("</div>")
        lines.append("</section>")
        lines.append("")

    md_path.write_text("\n".join(lines), encoding="utf-8")


def sync_docs(config: CourseSiteConfig):
    config.docs.mkdir(exist_ok=True)

    for source, output_name in config.site_source_pages.items():
        destination = config.docs / output_name
        if source == config.learning_objectives_file:
            lines = source.read_text(encoding="utf-8").splitlines()
            normalized_lines = [line.rstrip() for line in lines]
            while normalized_lines and not normalized_lines[-1]:
                normalized_lines.pop()
            destination.write_text(
                "\n".join(normalized_lines) + "\n",
                encoding="utf-8",
            )
        else:
            destination.write_bytes(source.read_bytes())

    return len(config.site_source_pages)


def main(config: CourseSiteConfig | None = None):
    config = config or CourseSiteConfig.for_repo(Path.cwd(), "COURSE")
    config.generated_outputs.mkdir(exist_ok=True)
    include_instructor_flags = not is_public_site_build(config.public_env_var)

    important_dates = parse_important_dates(config.important_dates_file, config.term_year)
    meeting_patterns = parse_meeting_patterns(
        config.lecture_schedule_file,
        config.lab_schedule_file,
    )
    objectives_by_code, objectives_by_tag = parse_learning_objectives(config.learning_objectives_file)
    quiz_rows = parse_quiz_schedule(config.quiz_schedule_file)
    assessment_rows = parse_additional_assessment_schedule(config.quiz_schedule_file)
    homework_rows = parse_homework_schedule(config.homework_schedule_file)
    exception_rows = parse_exception_events(config.exceptions_file, config.term_year)
    lecture_rows = parse_lecture_summary(config.lecture_file, quiz_rows)
    lecture_rows = assign_course_dates(lecture_rows, important_dates, meeting_patterns, config.term_year)
    assessment_rows = assign_additional_assessment_dates(
        assessment_rows,
        lecture_rows,
        important_dates,
        meeting_patterns,
        config.term_year,
    )
    lab_rows = parse_lab_summary(config.lab_file)
    annotate_prerequisite_flags(
        lecture_rows,
        lab_rows,
        objectives_by_code,
        objectives_by_tag,
        important_dates,
        meeting_patterns,
        config.term_year,
    )

    term_start, _ = term_bounds(important_dates, config.term_year)
    df = build_week_table(lecture_rows, lab_rows, assessment_rows, exception_rows, term_start)
    write_schedule_table(df, config.xlsx_file, config.output_sheet)
    write_markdown_table(df, config.output_md, include_instructor_flags)
    write_calendar_markdown(
        lecture_rows,
        lab_rows,
        homework_rows,
        assessment_rows,
        exception_rows,
        important_dates,
        meeting_patterns,
        config.output_calendar_md,
        include_instructor_flags,
        config.term_year,
    )
    calendar_events = build_calendar_events(
        lecture_rows,
        lab_rows,
        homework_rows,
        assessment_rows,
        exception_rows,
        important_dates,
        meeting_patterns,
        include_instructor_flags,
        config.term_year,
    )
    write_ics_calendar(calendar_events, config.output_ics, config)
    synced_docs = sync_docs(config)

    mode = "instructor" if include_instructor_flags else "public"
    print(f"Processed {len(lecture_rows)} lecture entries, {len(lab_rows)} lab/project entries, and {len(exception_rows)} exception event(s).")
    print(f"Build mode: {mode}")
    print(f"Wrote {len(df)} rows to {config.xlsx_file.name} -> {config.output_sheet}")
    print(f"Wrote markdown schedule to {config.output_md.name}")
    print(f"Wrote calendar view to {config.output_calendar_md.name}")
    print(f"Wrote calendar download to {config.output_ics.name}")
    print(f"Synced {synced_docs} site source files to {config.docs.name}/")


if __name__ == "__main__":
    main()
